version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: pm2-dev ./app/app.js
    environment:
      NODE_ENV: development
    links:
      - mariadb
    env_file: ./.env
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    volumes:
      - .:/usr/src/app
      - ./node_modules:/home/nodejs/node_modules

  mariadb:
    image: mariadb:latest
    env_file: ./.env
    volumes:
      - maria-data:/data/db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    ports:
      - ${MYSQLDB_PORT}:${MYSQLDB_PORT}

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    restart: always
    ports: 
      - "8080:8080"

volumes:
  maria-data: